### ISSUE TITLE
Upgrade default Alfresco version to 5.1.f and RM to 2.4.b

### ISSUE THREAD

**Issue by slanglois** [Alfresco/alfresco-sdk#375] opened 2016-04-27 08:29 UTC
We just released Alfresco Community 201604 / 5.1.f
It would be nice to upgrade the default version the SDK depends on from 5.1.e to 5.1.f

Also, RM 2.4.b was just released too. Be careful that its packaging is a bit different now, so the artifactId will probably need to change.

**Comment by slanglois** [comment] 2016-04-27 08:46
Damn... The location of Surf changed, so a simple upgrade to 5.1.f doesn't work.

    [INFO] project created from Archetype in dir: D:\work\alfresco-sdk\archetypes\share-amp-archetype\target\test-classes\projects\run-b asic\project\shareAmpTestRun
    [INFO] Invoking post-archetype-generation goals: verify -Pamp-to-war -Dmaven.tomcat.fork=true
    [INFO] [INFO] Error stacktraces are turned on.
    [INFO] [INFO] Scanning for projects...
    [INFO] [ERROR] [ERROR] Some problems were encountered while processing the POMs:
    [INFO] [ERROR] 'dependencies.dependency.version' for org.springframework.extensions.surf:spring-surf-api:jar is missing. @ line 76,  column 21
    [INFO]  @
    [INFO] [ERROR] The build could not read 1 project -> [Help 1]
    [INFO] org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
    [INFO] [ERROR] 'dependencies.dependency.version' for org.springframework.extensions.surf:spring-surf-api:jar is missing. @ line 76,  column 21

**Comment by gravitonian** [comment] 2016-04-27 09:09
Hi,

I am writing some new Alfresco version upgrade docs. So will look into this also, so it is included in the docs.

**Comment by loftux** [comment] 2016-05-03 05:48
The error listed by @slanglois can easily be fixed by changing the dependency in share amp project to 

        <dependency>
            <groupId>org.alfresco.surf</groupId>
            <artifactId>spring-surf-api</artifactId>
            <scope>provided</scope>
        </dependency>

Change the groupId from org.springframework.extensions.surf to org.alfresco.surf, think you already know this but adding if anyone else run into this and need a workaround.

I still get another error:   

    [ERROR]   The project test.loftux.se:coolrunnings-share-amp:1.0-SNAPSHOT (/Users/peter/temp/sdktest/coolrunnings/coolrunnings-share-amp/pom.xml) has 1 error
    [ERROR]     'dependencies.dependency.version' for org.alfresco.surf:spring-surf-api:jar must be a valid version but is '${dependency.surf.version}'. @ org.alfresco:alfresco-platform-distribution:[unknown-version], /Users/peter/.m2/repository/org/alfresco/alfresco-platform-distribution/5.1.f/alfresco-platform-distribution-5.1.f.pom, line 195, column 18   

So it is missing the dependency.surf.version, I've tried to add this to the properties section in pom.xml, but that doesn't get picked up. The only way I could get it to work is with adding to command line:   

    mvn clean install -Prun -Ddependency.surf.version=6.3   

With this I can run the sdk with 5.1.f. Would be better if the dependency surf version could be picked up from the share version used, else it may be overlooked when Share version is updated.

**Comment by gravitonian** [comment] 2016-05-03 06:41
New Alfresco version upgrade docs: http://docs.alfresco.com/5.1/concepts/alfresco-sdk-upgrading-alfresco-version.html

**Comment by tom-vandepoele** [comment] 2016-06-24 10:02
Just a heads up, the same problem occurs when you generate a 5.1.0.5 project using the maven archetype.

(You need to fix the groupId to org.alfresco.surf and run with -Ddependency.surf.version=6.3)

**Comment by deas** [comment] 2016-07-15 06:56
Seems there is no way to apply something similar to `-Ddependency.surf.version=6.3` within an IDE context. Personally I use Intellij, and I see really nasty effects due to classes which cannot be resolved. Would be nice to get this fixed in the pom and propagated to the maven repos.

**Comment by philandrews-ixxus** [comment] 2016-09-01 14:22
@deas I was just poking this issue and my workaround was to hoist spring-surf and spring-surf-api to the <dependencyManagement> section of my pom like this:

`<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.alfresco.surf</groupId>
                <artifactId>spring-surf</artifactId>
                <version>${dependency.surf.version}</version>
            </dependency>
            <dependency>
                <groupId>org.alfresco.surf</groupId>
                <artifactId>spring-surf-api</artifactId>
                <version>${dependency.surf.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>`

I have multiple share modules in my project so I did this in my project's root pom just added those dependencies under alfresco-platform-distribution but it does work if you do it directly in the share module pom.  Now you can set the property directly in your project pom and have it recognized by maven without having to pass it on the command line.

**Comment by deas** [comment] 2016-09-01 14:50
@philandrews-ixxus IIRC, this workaround only helped with the command line and the problem with IntelliJ resolving classes/resources remained. I think I ended up fixing the root cause of the issue in the pom.

**Comment by fshipley** [comment] 2016-09-08 07:51
I have this issue too. It looks like the `dependency.surf.version` property is not declared anywhere in the `alfresco-platform-distribution` pom nor in its parent pom (`alfresco-parent`). It should probably be declared in the `alfresco-parent` pom along with the other properties such as `dependency.spring.version` etc. See: https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/alfresco-parent/5.1.g/alfresco-parent-5.1.g.pom.

The only workaround I found to avoid having to specify `-Ddependency.surf.version=6.5` on the command line was to add the surf dependencies to the `<dependencyManagement>` section in my local pom. Thanks @philandrews-ixxus.

**Comment by michaeljmuller** [comment] 2016-10-25 23:30
I had the same problem as others getting this to build in my IDE (eclipse).  Thank you @philandrews-ixxus for the workaround!

**Comment by ohej** [comment] 2017-03-24 11:28
SDK3 offers a much easier way of dealing with dependencies, like RM. Closing the issue, feel free to reopen if this issue still persists in SDK3.

**Closed by ohej** 2017-03-24 11:28 UTC

**Comment by anakin59490** [comment] 2017-12-06 15:55
I use Eclipse but "Maven> Update project" command doesn't work : "Missing artifact org.alfresco.surf:spring-surf:jar:${dependency.surf.version}"
I try to define the  dependency.surf.version in settings.xml file (~.m2 folder) without success. Is it possible to do it ? Thx

**Comment by anakin59490** [comment] 2017-12-07 09:57
OK resolve with comment above :  "philandrews-ixxus commented on 1 Sep 2016 "
