### ISSUE TITLE
AIO wrongly includes many libraries in the share-amp module's AMP

### ISSUE THREAD

**Issue by Sheldor5** [Alfresco/alfresco-sdk#300] opened 2015-06-04 19:55 UTC
It seems the share-amp sub module from the AIO archetype includes share libraries when packaging the amp. Tried with a fresh AIO project and inside the share-amp-1.0-SNAPSHOT.amp in the libs folder there are 40 jar files:

xml-apis-1.4.01.jar
xercesImpl-2.10.0-alfresco-patched.jar
xalan-2.7.2.jar
webbit-0.4.14.jar
share-amp.jar
serializer-2.7.2.jar
selenium-support-2.45.0-alfresco.jar
...

These jar files are also getting copied inside the target\share-amp\lib folder.

The standalone Share-AMP archetype is working fine.

SDK 2.1.0

**Comment by mindthegab** [comment] 2015-06-04 23:02
Ouch this is a nasty one...might require a quick fix and release because it can create real havoc and requires the amp to use -force ...

Ugly...

**Comment by ohej** [comment] 2015-06-08 06:55
I suspect this is related to the regression testing. @gravitonian could you dig into this one? It's probably a matter of setting the proper scope for those dependencies.

**Comment by manoswerts** [comment] 2015-06-10 09:46
The same problem occurs with the `alfresco-amp-archetype`. When executing `clean install`, the correct libraries are included. When executing the `amp-to-war` profile, a lot of extra libraries are included that clash when applying the AMP:

* alfresco-rad-2.1.0.jar
* args4j-2.0.16.jar
* jetty-continuation-7.4.0.v20110414.jar
* jetty-http-7.4.0.v20110414.jar
* jetty-io-7.4.0.v20110414.jar
* jetty-security-7.4.0.v20110414.jar
* jetty-server-7.4.0.v20110414.jar
* jetty-servlet-7.4.0.v20110414.jar
* jetty-util-7.4.0.v20110414.jar
* junit-remote-3.jar
* slf4j-api-1.7.7.jar
* spring-test-3.0.6.RELEASE.jar

Tested in 2.0.0 and 2.1.0. This is indeed nasty one. It does not allow us to install the AMP without using the `-force` parameter.

**Comment by gravitonian** [comment] 2015-06-10 10:08
For share-amp in AIO, add scope test to selenium:

   <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>2.45.0-alfresco</version>
            <scope>test</scope>
        </dependency>

https://issues.alfresco.com/jira/browse/DEVPLAT-107

**Comment by gravitonian** [comment] 2015-06-10 10:42
For the repo-amp project we need to update the amp-to-war profile a bit. And remove the alfresco-rad dependency from repo-amp project, see https://issues.alfresco.com/jira/browse/DEVPLAT-108.
Meanwhile use mvn clean install to produce the deliverable, or add a new profile amp-to-war2 for the repo-amp/pom.xml as in the DEVPLAT and then use it instead.

**Comment by mindthegab** [comment] 2015-06-10 11:42
It's perfectly OK to have deps if you run with a profile.

The deliverable should always and ONLY produced with mvn clean install while -Pamp-to-war is a local only profile to be used for dev.

IMHO DEVPLAT-108 can be closed

**Comment by mindthegab** [comment] 2015-06-10 11:43
And also this one if you fixed the issue introduced in the share side by the wrong dep scope...

**Comment by manoswerts** [comment] 2015-06-10 11:44
@mindthegab,

I do not agree with that. We use that `amp-to-war` profile to run automated integration tests against the embedded Tomcat server. Our build server makes sure that the build is successful (therefore running the integration tests) and then releases the artifact.

**Comment by mindthegab** [comment] 2015-07-30 18:25
@manoswerts Let's keep this and #307 separate.

This is a bug about  the wrong scope in the share amp profile, #300 is an enhancement in the behavior of amp-to-war. Let's keep on discussing there @manoswerts while @ohej and @gravitonian can you verify this bug is fixed by 2.1.1-SNAPSHOT/

**Comment by manoswerts** [comment] 2015-07-31 06:07
Ok, great. Thank you for separating the issues.

**Closed** 2015-08-26 10:44 UTC
Labels: bug

**Comment by douglascrp** [comment] 2015-10-21 00:27
Is this supposed to be fixed on 2.1.1?

I's using SDK 2.1.1 here, and my final amp created using mvn clean install -DskipTests=true is still a huge file, with 36 MB, basically jar files.

**Comment by mindthegab** [comment] 2015-10-21 04:09
Not for me.

Just did:

1. mvn archetype:generate -Dfilter=org.alfresco: 
2. Selected share
3. mvn clean install -DskipTests=true
4. The AMP only contains a single JAR of the classes

How did you update to 2.1.1? In this case the change is on the generated POM (basically you need to add scope test to selenium-java), maybe you just updated the parent pom reference?

**Comment by douglascrp** [comment] 2015-10-21 09:25
I have simply updated the parent pom version.
I'm going to try again tonight.
Thank you

**Comment by douglascrp** [comment] 2015-10-21 12:25
@mindthegab you were right... the scope config for selenium-java did the trick.

Based on that, I think it would be right to include that info into this page http://docs.alfresco.com/community/tasks/alfresco-sdk-upgrading-sdkversion-210-211.html
as this affirmation is not completely right: "You can upgrade any extension project from using SDK version 2.1.0 to using SDK version 2.1.1 simply by changing the version number in the top-level POM file."

Thank you for your help.

**Comment by jgoldhammer** [comment] 2016-11-26 22:20
Ole,

since this is fixed for share, we can close the ticket.

@ohej : How can we trigger documentation updates for docs.alfresco.com? JIRA Issue in issues.alfresco.com??
