### ISSUE TITLE
"Unable to validate database schema" error when starting Alfresco the first time

### ISSUE THREAD

**Issue by slanglois** [Alfresco/alfresco-sdk#245] opened 2014-12-19 16:06 UTC
Found when testing 2.0.0
Whenever Alfresco is started the first time (whether through the amp archetype or the all-in-one), one gets the following stack:

    2014-12-19 15:54:33,187  WARN  [domain.schema.SchemaBootstrap] [localhost-startStop-1] Schema validation found 737 potential problems, results written to: d:\work\archetype\2.0-amp\target\Alfresco\Alfresco-H2Dialect-Validation-Post-Upgrade-alf_-726230537553783172.txt
    2014-12-19 15:54:33,376  WARN  [domain.schema.SchemaBootstrap] [localhost-startStop-1] Schema validation found 760 potential problems, results written to: d:\work\archetype\2.0-amp\target\Alfresco\Alfresco-H2Dialect-Validation-Post-Upgrade-jbpm_-8257004340912646122.txt
    2014-12-19 15:54:33,516  ERROR [domain.schema.SchemaBootstrap] [localhost-startStop-1] Unable to validate database schema.
    java.lang.IllegalArgumentException: dbObject cannot be null.
        at org.alfresco.util.schemacomp.DbProperty.<init>(DbProperty.java:51)
        at org.alfresco.util.schemacomp.DbProperty.<init>(DbProperty.java:113)
        at org.alfresco.util.schemacomp.model.AbstractDbObject.diff(AbstractDbObject.java:175)
        at org.alfresco.util.schemacomp.model.Table.doDiff(Table.java:220)
        at org.alfresco.util.schemacomp.model.AbstractDbObject.diff(AbstractDbObject.java:178)
        at org.alfresco.util.schemacomp.DefaultComparisonUtils.compareCollections(DefaultComparisonUtils.java:208)
        at org.alfresco.util.schemacomp.model.Schema.doDiff(Schema.java:181)
        at org.alfresco.util.schemacomp.model.AbstractDbObject.diff(AbstractDbObject.java:178)
        at org.alfresco.util.schemacomp.SchemaComparator.compare(SchemaComparator.java:66)
        at org.alfresco.util.schemacomp.SchemaComparator.validateAndCompare(SchemaComparator.java:57)
        at org.alfresco.repo.domain.schema.SchemaBootstrap.attemptValidateSchema(SchemaBootstrap.java:1920)
        at org.alfresco.repo.domain.schema.SchemaBootstrap.validateSchema(SchemaBootstrap.java:1862)
        at org.alfresco.repo.domain.schema.SchemaBootstrap.validateSchema(SchemaBootstrap.java:1849)
        at org.alfresco.repo.domain.schema.SchemaBootstrap.onBootstrap(SchemaBootstrap.java:1749)

It doesn't seem to prevent it from starting, though...

**Comment by trycoon** [comment] 2015-01-27 08:13
I get the same exception. When converting our project to SDK 2.0.0. I don't know what implications this error has upon our project, but it would be nice it if could be fixed. ++

**Comment by jgoldhammer** [comment] 2015-03-02 07:34
Got the same exception here...

**Comment by skopf** [comment] 2015-03-03 16:49
Same here

**Comment by mindthegab** [comment] 2015-03-03 17:14
This is a dupe of https://github.com/Alfresco/alfresco-sdk/issues/250

**Closed by mindthegab** 2015-03-03 17:14 UTC
