### ISSUE TITLE
share-amp-archetype no longer includes "web" folder

### ISSUE THREAD

**Issue by Sheldor5** [Alfresco/alfresco-sdk#302] opened 2015-06-05 15:16 UTC
The share-amp-archetype no longer includes the src/main/amp/web folder at packaging the amp. But the folder gets copied into the /target/(build.finalName) folder and the resources are minified as well.

SDK 2.1.0

**Comment by Sheldor5** [comment] 2015-06-07 16:31
Okay it seems that `mvn install` works but `mvn integration-test` still won't package the web folder in the AMP.

**Comment by ohej** [comment] 2015-06-08 06:51
Did you try doing a "mvn clean package" ? The key is to do a clean before you package/deploy. 

To get the RAD/hot reloading features working with static resources we've had to do some creative moving files around. 

This is something we are addressing long term, but requires some fixes in the product (like https://issues.alfresco.com/jira/browse/MNT-13942).

Could you verify that doing a clean solves your problem?

**Comment by Sheldor5** [comment] 2015-06-08 09:36
The `clean` phase is always used. The problem is that I can't see my customizations if the `integration-test` does not include my JavaScript libraries and resources inside the web folder. How else can I see the results of my customizations?

I haven't used the hot reloading feature yet.

**Comment by ohej** [comment] 2015-06-08 09:50
Okay, then I don't fully understand the issue. Are we talking about the web folder not being inside the AMP file that is produced, or are we talking about the files in the web folder not being available when running the project?

I've just created a Share project from the 2.1.0 share-amp-archetype. By default it comes with a sample widget ``src/main/amp/web/js/example/widgets/TemplateWidget.js``

When running the Share project (``mvn integration-test -Pamp-to-war`` or ``./run.sh``) the file is available via the browser (http://localhost:8081/share/js/example/widgets/TemplateWidget.js).

The files in ``src/main/amp/web`` are not installed in the target war file (``/target/${artifactId}-war``). We specifically do not do this to allow hot reloading and have good IDE integration. 

The tomcat context file (``tomcat/context.xml``) maps the ``target/${artifactId}/web`` folder as part of a virtual webapp. It has been like this since 2.0.

Again, I'm not sure I fully understand the problem? It might be easier if you describe steps to reproduce the problem.

**Comment by Sheldor5** [comment] 2015-06-08 12:46
Okay this is my mistake I am very sorry! I was confused where the web folder is that I haven't even checked if the resources are available! So only the `package` or `install` phase actually packages the web folder inside the amp? Is this documented anywhere?

**Comment by ohej** [comment] 2015-06-09 07:47
Package and install will include the resources, the "amp-to-war" (for the AMP archetypes) or "run" (all in one) profiles will mess a bit with the web folder. Just make sure to do a clean and do not activate those profiles when building your artifacts.

I have added a comment on https://issues.alfresco.com/jira/browse/DEVPLAT-73 to get this process documented. Closing the issue

**Closed by ohej** 2015-06-09 07:47 UTC
