### ISSUE TITLE
Subsystem property injections ignored while using local/alfresco-global.properties

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#360] opened 2016-02-19 13:26 UTC

**Comment by ohej** [comment] 2016-02-19 15:35
Any chance you could explain a bit more about what the issue exactly is?

**Comment by bhagyas** [comment] 2016-02-19 15:37
Created a subsystem within the repo-amp and wanted to inject properties using ${} notation.

The properties were defined in repo-amp/src/test/properties/local/alfresco-global.properties.

The instantiated beans don't seem to be picking up the properties.

**Comment by ohej** [comment] 2016-02-19 15:39
Have you tried defining the properties in repo/src/main/properties/local/alfresco-global.properties?

**Comment by bhagyas** [comment] 2016-02-19 15:40
No.

**Comment by ohej** [comment] 2016-02-19 15:41
Would you like to try it and report back?

**Comment by bhagyas** [comment] 2016-02-19 15:43
Sure.

**Comment by bhagyas** [comment] 2016-02-26 09:39
The suggested approach did not work.

**Comment by rgauss** [comment] 2016-02-26 11:11
@bhagyas, do you have default values defined in a subsystem properties file?

**Comment by bhagyas** [comment] 2016-02-26 12:02
Yes.

**Comment by gravitonian** [comment] 2016-02-29 07:33
Subsystem properties override alfresco-global.properties so closing as not a bug

**Comment by gravitonian** [comment] 2016-03-01 13:41
Just clarifying exactly what subsystem files override what to avoid confusion.

For example, if you have the following subsystem properties config file in a Repo AMP:

`repo-amp/src/main/amp/config/alfresco/extension/subsystems/email/OutboundSMTP/outbound/outboundSMTP.properties
` 
Then it will take precedence over default subsystem configuration in a Repo AMP:
 
`/alfresco/extension/subsystems/<category>/default/default`

Which takes precedence over:
 
`alfresco-global.properties`

Which takes precedence over default property values set in:

`webapps/alfresco/WEB-INF/classes/alfresco/subsystems/<category>/<type>/<id>`

Note also, any setting via JMX goes into the database and takes precedence over everything else above.

**Comment by bhagyas** [comment] 2016-03-01 13:53
This issue needs to be reopened. 

Please understand and go through the history of an issue before closing.

**Comment by bhagyas** [comment] 2016-03-01 13:55
The issue is specific to the SDK, most probably due to the classpaths for subsystems being isolated and set by code instead of configuration.

**Comment by ohej** [comment] 2016-03-01 13:56
Reopening. Can you please explain EXACTLY what you are trying to do? Provide an example. Even after re-reading the issue I still don't understand what the issue is.

**Comment by bhagyas** [comment] 2016-03-01 13:57
I wanted to inject a property to a spring configuration file within a subsystem being developed with SDK.

The defined properties for subsystem spring files doesn't get injected during bean initialisation.

**Comment by gravitonian** [comment] 2016-03-01 14:15
Hi, 

Can you have a look at the subsystem dev docs, which include a custom subsystem implementation with sample code, and see if they give you any clues to what is going wrong: http://docs.alfresco.com/5.1/references/dev-extension-points-custom-subsystem.html

**Comment by rgauss** [comment] 2016-03-01 14:32
I can confirm that things work as expected in the SDK.

See [this forthcoming SDK sample](https://github.com/Alfresco/alfresco-sdk-samples/tree/new-samples-with-tests/all-in-one/custom-subsystem-repo).

You can override the subsystem values in `repo/src/main/properties/local/alfresco-global.properties` as mentioned above.

Make sure you have defaults defined in a subsystem properties file, also mentioned above.

**Comment by bhagyas** [comment] 2016-03-01 14:40
Thanks. In this case it has been a custom authentication module within the Authentication subsystem. 

Are there any naming conventions for property naming for such submodules within a subsystem?

In comparison with the SDK samples which only consist of a repo-amp module, this instance was run using all-in-one runner module.

**Comment by rgauss** [comment] 2016-03-01 14:56
> Are there any naming conventions for property naming for such submodules within a subsystem?

You could follow precedence of the [existing Authentication subsystems](https://svn.alfresco.com/repos/alfresco-open-mirror/alfresco/HEAD/root/projects/repository/config/alfresco/subsystems/Authentication/).

> this instance was run using all-in-one

That's what I've used as well.

**Comment by bhagyas** [comment] 2016-03-01 15:11
Is the naming convention tied to property injection mechanism? If not, I guess we can be pretty sure that's not the reason.

**Comment by rgauss** [comment] 2016-03-01 15:46
> Is the naming convention tied to property injection mechanism?

It should not be.  Just be sure your property names are exactly the same in your spring beans, subsystem property files, and alfresco-global.properties, and that they don't conflict with existing property names.

**Closed** 2017-03-24 11:13 UTC
