### ISSUE TITLE
Integration test tries to use MySQL, not H2

### ISSUE THREAD

**Issue by lutzhorn** [Alfresco/alfresco-sdk#414] opened 2016-09-29 09:15 UTC
Under SDK 3.0.0Running a unit test like

```
@RunWith(RemoteTestRunner.class)
@Remote(runnerClass = SpringJUnit4ClassRunner.class)
@ContextConfiguration("classpath:alfresco/application-context.xml")
public class MyTest {

    @Autowired
    @Qualifier("ServiceRegistry")
    private ServiceRegistry serviceRegistry;

    @Test
    public void myTest() {
        NodeService nodeService = serviceRegistry.getNodeService();
        // Use nodeService to do stuff with nodes.
    }
}
```

with `mvn test` this results in

```
2016-09-29 11:05:12,787  INFO  [alfresco.repo.admin] [main] Using database URL 'jdbc:mysql://localhost:3306/ALF_UNIT_TEST' with user 'ALF_UNIT_TEST'.
 Cannot load JDBC driver class 'org.gjt.mm.mysql.Driver'
java.lang.ClassNotFoundException: org.gjt.mm.mysql.Driver
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
```

The `pom.xml` contains the unchanged H2 configuration.

**Comment by lutzhorn** [comment] 2016-09-29 09:17
Using SDK 2.2.0 for Alfresco 5.1e this kind of test works fine and uses H2.

**Comment by gravitonian** [comment] 2016-09-30 11:14
We are working on the test bit

**Comment by ohej** [comment] 2017-03-23 16:08
Can't reproduce with the latest changes to testing, closing

**Closed by ohej** 2017-03-23 16:08 UTC
