### ISSUE TITLE
Alfresco repository does not install an enterprise licence because it detects mutliple license files (alfresco sdk 3 beta 1)

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#395] opened 2016-08-24 22:42 UTC
Result:
The alfresco repository runs as trial version!

The output of the alfresco repository is the following:

` 2016-08-25 00:37:10,517  WARN  [enterprise.license.AlfrescoLicenseManager] [DefaultScheduler_Worker-2] Found more than one license file to install. The licenses found are: [file [/Users/jgoldhammer/development/sources/alfrescosdk3-repo/target/tomcat/webapps/alfrescosdk3-repo-platform/WEB-INF/classes/alfresco/extension/license/Alfresco-ent51-xxx.lic]] [file [/Users/jgoldhammer/development/sources/alfrescosdk3-repo/target/classes/alfresco/extension/license/Alfresco-ent51-xxx.lic]]
`

License file is located inside src/main/resources/alfresco/extension/license

![image](https://cloud.githubusercontent.com/assets/3872101/17950642/c0ce66b0-6a5c-11e6-9703-cabcd21e02d3.png)

**Comment by gravitonian** [comment] 2016-09-05 14:45
Cannot reproduce following docs: https://docs.google.com/document/d/1p5QR1Q8pVvMT9fh_aID5nraD5NP6ZrU1ztcgE_zHR-4/pub#h.de36riszvp2d (for AIO), and https://docs.google.com/document/d/1p5QR1Q8pVvMT9fh_aID5nraD5NP6ZrU1ztcgE_zHR-4/pub#h.g8ulc75vtjb7 (for Platform JAR)

**Comment by jgoldhammer** [comment] 2016-09-05 15:14
I do not like that you have closed the issue without asking or just trying to find the root cause together with me. It does not help me indeed.

**Comment by ohej** [comment] 2016-09-05 20:32
I haven't been able to reproduce the issue, but I have a hunch on what the issue might be. @jgoldhammer can you share your pom.xml? even better if you are able to share the whole project, but understand if that's not possible ;)

**Comment by gravitonian** [comment] 2016-09-06 06:58
Hi,

Sorry for closing the issue too early! I can actually reproduce this now. You just need to wait a minute or two after Alfresco has started. Then it prints the log as above:

` 2016-09-05 15:44:25,476  WARN  [enterprise.license.AlfrescoLicenseManager] [DefaultScheduler_Worker-3] Found more than one license file to install. The licenses found are: [file [/home/martin/src/sdk3/alfresco-sdk-tests/platform-jar/target/tomcat/webapps/platform-jar-platform/WEB-INF/classes/alfresco/extension/license/Ent5.1-AllEnabled-Exp01012017.lic]] [URL [jar:file:/home/martin/src/sdk3/alfresco-sdk-tests/platform-jar/target/tomcat/webapps/platform-jar-platform/WEB-INF/lib/platform-jar-1.0-SNAPSHOT.jar!/alfresco/extension/license/Ent5.1-AllEnabled-Exp01012017.lic]] [file [/home/martin/src/sdk3/alfresco-sdk-tests/platform-jar/target/classes/alfresco/extension/license/Ent5.1-AllEnabled-Exp01012017.lic]] 
`

This is because, first the build process moves the license into the exploded WAR dir. Then it is packaged into the Platform JAR, that is also added to the WAR. And then maven moves it over to target/classes when you build.

Let me think of some better way to solve it...

**Comment by gravitonian** [comment] 2016-09-06 08:22
Just committed a change that requires the license to be put in /src/test/license. It will then be copied into the WAR (WEB-INF/classes/alfresco/extension/license). And not be part of any other classpaths.

**Comment by jgoldhammer** [comment] 2016-09-06 08:59
Thanks all for finding the cause and fixing it. This way it makes fun to contribute...

**Closed** 2016-09-06 13:06 UTC
