### ISSUE TITLE
Spring Context and Classes are loaded twice with SDK 3 Platform JAR Archetype

### ISSUE THREAD

**Issue by gravitonian** [Alfresco/alfresco-sdk#483] opened 2017-10-02 08:15 UTC
## I'm submitting a 
```
[x ] bug report
[ ] feature request
```
## Expected Behavior
Classes and Spring Context are loaded once when running a Platform JAR project with alfresco:run.

## Current Behavior
Spring Context and Classes are loaded twice when running a Platform JAR project with alfresco:run.

## Possible Solution
One solution is to comment out the platform JAR in the platformModules section in the Alfresco Maven Plugin configuration:

```
        <plugin>
                <groupId>org.alfresco.maven.plugin</groupId>
                <artifactId>alfresco-maven-plugin</artifactId>
                <version>${alfresco.sdk.version}</version>
...
                <configuration>
...
                    <platformModules>
                        <!-- This AMP is needed if we are going to access the platform webapp from a Share webapp -->
                        <!-- Share Services will be ignored if you are on Platform earlier than 5.1 -->
                        <moduleDependency>
                            <groupId>${alfresco.groupId}</groupId>
                            <artifactId>alfresco-share-services</artifactId>
                            <version>${alfresco.share.version}</version>
                            <type>amp</type>
                        </moduleDependency>

                        <!-- Comment out this JAR project, so things are not loaded twice

                        <moduleDependency>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                            <version>${project.version}</version>
                        </moduleDependency>

                        -->
                    </platformModules>
                </configuration>
            </plugin>
```

Another solution is to use an All-in-One (AIO) project as it would only load sub-project JARs from the assembled WAR.

Note. by commenting out the JAR from the Alfresco Maven plugin configuration it does not end up in alfresco/WEB-INF/lib during runtime, and hence resources from the project's /META-INF directory might not be loaded correctly.

To solve this permanently for Platform JAR projects it might be possible to produce two artifacts when building, one with just resources that is included by the Alfresco Maven plugin, and the artifact that is currently produced, which can be distributed.

## Steps to Reproduce (for bugs)
It is possible to use a scheduled job example to point out the problem:

1. Generate a Platform JAR project with SDK 3.0.1
2. Navigate to http://docs.alfresco.com/5.1/references/dev-extension-points-scheduled-jobs.html page
3. Create a class in the project based on the ScheduledJobExecuter class on docs page
4. Create a class in the project based on the ScheduledJob class on docs page
5. Add the <bean id="org.alfresco.tutorial.scheduledjob.actions.ScheduledJobExecuter"
6. Add the <bean id="org.alfresco.tutorial.scheduledjob.jobDetail"
7. Add the <bean id="org.alfresco.tutorial.scheduledjob.trigger"
8. Add the <bean class="org.springframework.scheduling.quartz.SchedulerFactoryBean"
9. Add to modules alfresco-global.properties: org.alfresco.tutorial.scheduledjob.cronexpression=0 0/2 * * * ?
org.alfresco.tutorial.scheduledjob.cronstartdelay=240000
10. Turn on debug log so logging from classes are visible
11. Run with $ mvn clean install alfresco:run
12. You should see the scheduled job executed twice every time it is triggered

Note. that in point 8 the bean does not have an ID, which means that if the Spring context is loaded twice that bean will not be overwritten the second time around. If no name is supplied explicitly, the container will generate a unique name for that bean each time, loading it twice. Which is unfortunate in this case as it triggers jobs...

## Context
This was discovered when debugging why a scheduled job was executed twice in a Platform JAR Project but not in an AIO project.

## Your Environment

* Alfresco SDK 3.0.1 
* Platform JAR project with default configuration
* 
$ mvn -version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T20:39:06+01:00)
Maven home: /Users/mbergljung/Tools/apache-maven-3.5.0
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"

## Additional information
None

**Comment by tom-vandepoele** [comment] 2017-10-13 12:03
See https://github.com/Alfresco/alfresco-sdk/issues/450, this is a duplicate of that ticket.

**Comment by ohej** [comment] 2018-03-02 15:13
Closing as it's a duplicate of #450

**Closed by ohej** 2018-03-02 15:13 UTC
