### ISSUE TITLE
All-In-One Archetype / Repo-Amp fails on missing H2 script

### ISSUE THREAD

**Issue by ghernando** [Alfresco/alfresco-sdk#275] opened 2015-04-23 16:16 UTC
When building the repo-amp portion of the all-in-one maven archetype 2.0.0 for Alfresco 5.0.1, I am seeing the following error:

 2015-04-23 07:06:47,554  INFO  [domain.schema.SchemaBootstrap] [main] Connecting to database: jdbc:h2:./alf_data_dev/h2_data/alf_dev, UserName=ALFRESCO, H2 JDBC Driver
 2015-04-23 07:06:47,554  INFO  [domain.schema.SchemaBootstrap] [main] Schema managed by database dialect org.hibernate.dialect.H2Dialect.
 2015-04-23 07:06:51,844  ERROR [domain.schema.SchemaBootstrap] [main] Schema auto-update failed
 org.alfresco.error.AlfrescoRuntimeException: 03230004 Script [classpath:alfresco/dbscripts/upgrade/4.2/${db.script.dialect}/migrate-locale-multilingual.sql ] can't be found for class org.hibernate.dialect.H2Dialect

**Comment by gravitonian** [comment] 2015-04-27 11:05
Hi,

I did try this out by doing as follows:

$ mvn archetype:generate -Dfilter=org.alfresco.maven.archetype:

Selected all-in-one

Updated version to 5.0.1:

all-in-one200$ vi pom.xml
<alfresco.version>5.0.1</alfresco.version>

Then built it:

all-in-one200$ mvn clean install

Which worked, then tried running it:

all-in-one200$ mvn clean install -Prun,enterprise

Which also worked. Accessed and logged in via:

http://localhost:8080/share

Can you provide more information about exactly what steps you took?

**Comment by ghernando** [comment] 2015-04-27 19:10
I created the all-in-one via the Eclipse UI and Maven Central.
I then updated the main pom file by uncommenting the alfresco-groupId and alfresco_version, and updated the 5.0.1 version number.
The project didn't build correctly.
From the command prompt, I ran the following for the main project and subprojects:

mvn clean install -U

I see the error above when building the repo-amp -- actually when verifying it.

I can go back into Eclipse and run the main project and it does start up OK.
But from the command prompt, I can still see the error with the repo-amp.

**Comment by gravitonian** [comment] 2015-04-28 14:48
Note. If you have been running with 5.0.c it does not work to just change version to 5.0.1. When running with embedded tomcat upgrade does not work.
You have to first clear the database:
```
all-in-one200$ rm -rf alf_data_dev/ repo-amp/alf_data_dev/
```
Then do the builds again:
```
all-in-one200$ mvn clean install -Prun
```
or/and
```
all-in-one200/repo-amp$ mvn verify
```

**Comment by mindthegab** [comment] 2015-08-06 17:02
@ghernando Is this still an issue?

**Comment by avasyukov** [comment] 2016-01-14 10:08
Revisiting this issue - it exists for recent 5.1.d-EA. but does not exist for 5.1.c-EA.

Steps to reproduce:
1. Generate clean project
2. Uncomment alfresco.version and set it to 5.1.d-EA
3. Start with run.sh or whatever, see it crashing with
```
Script [ classpath:alfresco/dbscripts/create/${db.script.dialect}/AlfrescoCreate-AuthorizationTables.sql ] can't be found for class org.hibernate.dialect.H2Dialect
```

Recheck with 5.1.c-EA, see everything working.

**Comment by gravitonian** [comment] 2016-01-20 05:02
5.1 is not compatible with SDK 2.0 or 2.1. We are working on SDK 2.2, which will be compatible with 5.1, in fact you can clone the SDK project now and it should work with 5.1

**Comment by jimtomonto** [comment] 2016-02-29 20:32
I am trying to run all-in-one or the repo amp archetype with Version 5.0.3 and it fails to startup on missing H2Scripts.  If I change to Version 5.0.2 all starts perfectly.  Is there some difference in packaging of the Alfresco Repo that changed for 5.0.3 or is this some sort of SDK issue?  Is there any work around?  

Thanks

**Comment by ohej** [comment] 2016-02-29 20:44
@jimtomonto, in 4.2.5 and 5.0.3 we introduced a new table, which was a change that was incompatible with the SDK 1.1.1 / 2.0.x / 2.1.x. Please see #358 for more info. You will need to add a dependency to your project. Let me know if the instructions are not clear in #358.

**Comment by jimtomonto** [comment] 2016-03-01 20:35
Ok I was able to get things working although it is more complicated for me to get things to startup cleanly... but here goes:

1) Build new repo amp architype
2) Edit pom.xml:
  A) Under <properties> add:
          <alfresco.version>5.0.3</alfresco.version>

  B) Under <dependencies> add:
<dependency>
            <groupId>${alfresco.groupId}</groupId>
            <artifactId>alfresco-repository</artifactId>
            <version>${alfresco.version}</version>
            <classifier>h2scripts</classifier>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

  C) Add the following to the end of the pom.xml (note: do not set the maven.tomcat.version because it is in the parent pom)
	<build>
      <plugins>
        <plugin>
            <groupId>org.apache.tomcat.maven</groupId>
            <artifactId>tomcat7-maven-plugin</artifactId>
            
            <dependencies>
                <dependency>
                    <groupId>org.alfresco</groupId>
                    <artifactId>alfresco-repository</artifactId>
                    <version>${alfresco.version}</version>
                    <classifier>h2scripts</classifier>
                    <exclusions>
                        <exclusion>
                            <groupId>*</groupId>
                            <artifactId>*</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </plugin>
      </plugins>
	</build>

3) Do Maven -> Update Project -> Check the box for "Force Updates/Snapshots"

4) Run maven with goal: clean install integration-test -Ppurge,enterprise -Dmodule.log.level=DEBUG 

5) The previous step will fail with message:
[ERROR] Failed to execute goal org.apache.tomcat.maven:tomcat7-maven-plugin:2.2:run (run-embedded) on project customer-order-upgrade: Execution run-embedded of goal org.apache.tomcat.maven:tomcat7-maven-plugin:2.2:run failed: Plugin org.apache.tomcat.maven:tomcat7-maven-plugin:2.2 or one of its dependencies could not be resolved: Could not find artifact org.alfresco:alfresco-repository:jar:h2scripts:5.0.3 in sonatype-public (http://oss.sonatype.org/content/groups/public) -> 

6) Go to the <user home directory>\.m2\repository\org\alfresco\alfresco-repository\5.0.3 and manually delete all files in this directory

7) Run maven with goal: clean install integration-test -Pamp-to-war,enterprise -Dmodule.log.level=DEBUG 

8) Repo will startup cleanly

**Comment by jimtomonto** [comment] 2016-03-01 20:39
Ok I was able to get things working although it is more complicated than it probably should be... but here goes:

1) Build new repo amp architype
2) Edit pom.xml:
  A) Under <properties> add:
          <alfresco.version>5.0.3</alfresco.version>

  B) Under <dependencies> add:
<dependency>
            <groupId>${alfresco.groupId}</groupId>
            <artifactId>alfresco-repository</artifactId>
            <version>${alfresco.version}</version>
            <classifier>h2scripts</classifier>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

  C) Add the following to the end of the pom.xml
	<build>
      <plugins>
        <plugin>
            <groupId>org.apache.tomcat.maven</groupId>
            <artifactId>tomcat7-maven-plugin</artifactId>
            
            <dependencies>
                <dependency>
                    <groupId>org.alfresco</groupId>
                    <artifactId>alfresco-repository</artifactId>
                    <version>${alfresco.version}</version>
                    <classifier>h2scripts</classifier>
                    <exclusions>
                        <exclusion>
                            <groupId>*</groupId>
                            <artifactId>*</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </plugin>
      </plugins>
	</build>

3) Do Maven -> Update Project -> Check the box for "Force Updates/Snapshots"

4) Run maven with goal: clean install integration-test -Ppurge,enterprise -Dmodule.log.level=DEBUG 

5) The previous step will fail with message:
[ERROR] Failed to execute goal org.apache.tomcat.maven:tomcat7-maven-plugin:2.2:run (run-embedded) on project customer-order-upgrade: Execution run-embedded of goal org.apache.tomcat.maven:tomcat7-maven-plugin:2.2:run failed: Plugin org.apache.tomcat.maven:tomcat7-maven-plugin:2.2 or one of its dependencies could not be resolved: Could not find artifact org.alfresco:alfresco-repository:jar:h2scripts:5.0.3 in sonatype-public (http://oss.sonatype.org/content/groups/public) -> 

6) Go to the <user home directory>\.m2\repository\org\alfresco\alfresco-repository\5.0.3 and manually delete all files in this directory

7) Run maven with goal: clean install integration-test -Pamp-to-war,enterprise -Dmodule.log.level=DEBUG 

8) Repo will startup

**Comment by ohej** [comment] 2017-03-24 11:16
This is resolved in SDK3

**Closed by ohej** 2017-03-24 11:16 UTC
Labels: bug
