### ISSUE TITLE
Enable JS / CSS minification and Share "developemnt" profile

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#134] opened 2014-07-20 14:30 UTC
_From [colum...@gmail.com](https://code.google.com/u/100251676538566683892/) on July 10, 2013 07:05:38_

Introduce a -Pdev (or alternative -Prelease) profile to:

1. Automatically set surf in debug mode
2. prevent minification of JS

By default instead:

- provide minification for all JSes and CSS (like done for the Alfresco Maven build in private branches)

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=134_

**Comment by ohej** [comment] 2015-05-12 11:59
Duplicate of #269, closing this one

**Closed by ohej** 2015-05-12 11:59 UTC
Labels: bug, imported, Priority-Medium
