### ISSUE TITLE
3.0.0-beta-1 run.sh scripts fail

### ISSUE THREAD

**Issue by wrighting** [Alfresco/alfresco-sdk#390] opened 2016-08-24 07:41 UTC
When attempting to use run.sh on the AIO or platform projects I get the following error message (AIO):

```
[INFO] Reactor Summary:
[INFO] 
[INFO] AIO - SDK 3.0 Beta ................................. FAILURE [01:06 min]
[INFO] Alfresco Platform/Repository JAR Module ............ SUCCESS [01:19 min]
[INFO] Alfresco Share JAR Module .......................... SUCCESS [  3.560 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:36 min
[INFO] Finished at: 2016-08-24T08:06:01+01:00
[INFO] Final Memory: 62M/642M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.alfresco.maven.plugin:alfresco-maven-plugin:3.0.0-beta-1:run (default-cli) on project example: Unable to execute mojo: java.lang.reflect.InvocationTargetException: Plugin org.alfresco.maven.plugin:alfresco-maven-plugin:3.0.0-SNAPSHOT or one of its dependencies could not be resolved: Failure to find org.alfresco.maven.plugin:alfresco-maven-plugin:jar:3.0.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/orgalfresco-1037 was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-sdk-staging-plugin has elapsed or updates are forced -> [Help 1]
```
A workaround is to:
```
cd ~/.m2/repository/org/alfresco/maven/plugin/alfresco-maven-plugin
cp 3.0.0-beta-1/alfresco-maven-plugin-3.0.0-beta-1.jar 3.0.0-SNAPSHOT/alfresco-maven-plugin-3.0.0-SNAPSHOT.jar
You also need to edit the version in META-INF/maven/plugin.xml in the jar
cp 3.0.0-beta-1/alfresco-maven-plugin-3.0.0-beta-1.pom 3.0.0-SNAPSHOT/alfresco-maven-plugin-3.0.0-SNAPSHOT.pom
```

**Comment by ohej** [comment] 2016-08-24 09:26
Thanks for reporting this, it's a rather unfortunate error. I tracked it down to this line: https://github.com/Alfresco/alfresco-sdk/blob/sdk-3.0/plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/RunMojo.java#L60

We'll see if we can get it fixed and push out a beta-2 shortly.

**Comment by jgoldhammer** [comment] 2016-08-24 17:04
The same for me.

**Comment by gravitonian** [comment] 2016-08-25 06:57
Fixed in "Removed the need for SDK version in RunMojo" check-in, forgot to add this issue number in check-in comment

**Comment by ohej** [comment] 2016-08-25 18:07
Opening again to get test feedback.

@wrighting and @jgoldhammer we have just released 3.0.0-beta-2. Can you retest and verify that this issue has been solved? Please clean out `~/.m2/repository/org/alfresco/maven`

After cleaning that out, you need to change the URL in `settings.xml` to use the new staging repository. Change the `orgalfresco-1037` to `orgalfresco-1038` like this:

```
 <profile>
    <id>alfresco-dev</id>
        <repositories>
            <repository>
                <id>alfresco-sdk-staging</id>
                <url>https://oss.sonatype.org/content/repositories/orgalfresco-1038/</url>
            </repository>
        </repositories>
        <pluginRepositories>
            <pluginRepository>
                <id>alfresco-sdk-staging-plugin</id>
                <url>https://oss.sonatype.org/content/repositories/orgalfresco-1038</url>
            </pluginRepository>
        </pluginRepositories>
        <activation>
            <activeByDefault>true</activeByDefault>
        </activation>
  </profile>
```

_Note that this step is only required because we're running off the staging repositories and not doing full, permanent releases_

After this, simply change one line in your project pom.xml:
`<alfresco.sdk.version>3.0.0-beta-2</alfresco.sdk.version>`

Let me know if it works! I tested on a clean Linux VM and seems to work as intended

**Comment by jgoldhammer** [comment] 2016-08-25 18:39
Works for me.
Thanks @ohej!

**Comment by wrighting** [comment] 2016-08-31 08:58
Works for me as well - thanks @gravitonian and @ohej

**Comment by ohej** [comment] 2016-09-01 09:39
Thanks for confirming! Closing.

**Closed by ohej** 2016-09-01 09:39 UTC

**Comment by zhihailiu** [comment] 2016-09-01 19:44
Repository not found?
https://oss.sonatype.org/content/repositories/orgalfresco-1038/
404 - Repository with ID="orgalfresco-1038" not found
Repository with ID="orgalfresco-1038" not found

**Comment by ohej** [comment] 2016-09-02 08:49
@zhihailiu I've opened #399 to track this one. It looks like Maven Central has dropped the staging repository (for now apparent reason). I'm investigating. Let's move the discussion to #399
