### ISSUE TITLE
Share AMPs are reported twice in logs

### ISSUE THREAD

**Issue by gravitonian** [Alfresco/alfresco-sdk#351] opened 2016-01-12 13:07 UTC
2016-01-12 13:01:55,284  INFO  [config.packaging.ModulePackageManager] [localhost-startStop-1] Found 2 module package(s)
 2016-01-12 13:01:55,286  INFO  [config.packaging.ModulePackageManager] [localhost-startStop-1] Alfresco Share AMP Module, 1.0.1601121300, This is a sample Alfresco Share AMP project, depended upon by the share WAR module
Alfresco Share AMP Module, 1.0.1601121300, This is a sample Alfresco Share AMP project, depended upon by the share WAR module

This is because it finds the module.properties in multiple paths

**Comment by ohej** [comment] 2016-03-03 16:17
This has actually always been the case, it's just not until 5.1 that we became aware of this. It's mainly because of the way we setup the virtual classpath and copy everything into test-classes. Essentially the module exists in multiple places, and it's also the root cause for #340. With the current setup there's no real way to fix this.

SDK 3.0 will solve this issue.

**Comment by jgoldhammer** [comment] 2016-09-13 13:32
Any update here, @ohej ?

**Comment by ohej** [comment] 2016-09-13 13:53
Since we're not using the virtual classpath and the mix of normal classpath + test classpath anymore this issue should be resolved now.

I will keep it open so we can test towards the end to make sure we dont' regress it.

@jgoldhammer have you seen this issue with SDK 3?

**Comment by ohej** [comment] 2017-03-24 09:53
Issue was fixed by SDK3 since we no longer have the virtual classpath and the mix of `target/classes` and `target/test-classes`

**Closed by ohej** 2017-03-24 09:53 UTC
