### ISSUE TITLE
AVT clojars-dependencies

### ISSUE THREAD

**Issue by HansDeBal** [Alfresco/alfresco-sdk#253] opened 2014-12-29 14:32 UTC
Hi,

I am starting a project with Alfresco 5 (5.0.0.2) and I used the alfresco SDK 2.0.0 to set up my development environment. The AVT (Alfresco Validation Tool) is using some clojars-dependencies (clojurewerkz:neocons, org.flatland:useful, ...). But when maven tries to resolve these dependencies in Eclipse, the jars don't get downloaded and I am getting errors.

_Project build error: Unresolveable build extension: Plugin org.alfresco.maven.plugin:alfresco-maven-plugin:2.0.0 or one of its dependencies could not be resolved: The following artifacts could not be resolved: clojurewerkz:neocons:jar:3.0.0, org.flatland:useful:jar:0.10.6, jansi-clj:jansi-clj:jar:0.1.0, io.aviso:pretty:jar:0.1.12, org.clojars.pmonks:depends:jar:0.3.0, org.clojars.pmonks:multigrep:jar:0.2.0, org.clojars.pmonks:bookmark-writer:jar:0.1.0, org.clojars.pmonks:spinner:jar:0.2.0_

I am already googling for a couple of hours and I found some instructions on adding the startcom-certificates to my JDK (a standard Oracle JDK 7) on this link (http://stackoverflow.com/questions/4302686/import-startcom-ca-certificates-in-windows-jre) but it isn't resolving my issue.
I am using windows 8.1, Eclipse Luna, maven 3.2.5 and as I said a standard oracle JDK 7 (1.7u67).

I have 2 questions:
* can you reproduce this or is this a known issue and is there a solution?
* Is there a way to tell the SDK I don't want the AVT (since it is still experimental)?

Thanks!

**Comment by LukasKraushofer** [comment] 2015-02-02 13:00
adding the clojars.org repository to your pom.xml will fix the problem.
Why isn't this repo in the alfresco-sdk-parent pom ?

**Comment by pmonks** [comment] 2015-02-02 15:02
Because Maven is supposed to transitively read it from the pom of the ATV (and indeed does for many of us - we've had trouble reproducing this issue).

Cheers,
Peter

Apologes for speling & gramar erorrs - sent from mobil deivce

**Comment by pmonks** [comment] 2015-02-03 03:58
Which of course it can't, if the pom is only on clojars.  #sillyme

Apologes for speling & gramar erorrs - sent from mobil deivce

**Comment by HansDeBal** [comment] 2015-02-05 14:16
Adding the clojars-repo to the pom doesn't work. Tried that. Setting up a normal maven project (no SDK-based project) gives the same problem. Was just wondering if the Alfresco SDK contained something to fix this clojars-issue.

**Comment by andrm** [comment] 2015-07-31 12:49
I'm having the same problem, is there any other workaround for this?

**Comment by mindthegab** [comment] 2015-08-06 17:11
@ohej can we verify this and propose a workaround? Anyone has an obvious PR for this?

**Comment by pmonks** [comment] 2015-08-06 20:09
I'd be interested to hear if any of you have issues with this project: https://github.com/AlfrescoLabs/technical-validation-java-example.  If not, it would suggest the issue is specific to the Alfresco SDK, rather than Maven or Clojars.

**Comment by HansDeBal** [comment] 2015-08-11 07:05
Hi Peter,

In Februari I created a small (non Alfresco SDK) project with Clojars-dependencies and I had the same problem. So I think it's related to clojars and not to the Alfresco-SDK. However, you guys don't seem to have the problem. So somewhere there has to be a configuration-difference. Maybe some extra instructions need to be added for setting up an SDK-project to cope with these clojars-issues?

**Comment by andrm** [comment] 2015-08-12 08:20
Please disregard my comment as it was a local problem. I was using a local artifactory instance by default (maven settings). After removing it, it work. It may be helpful to include a note in the docs of the sdk.

**Comment by pmonks** [comment] 2015-08-12 16:11
@andrm interesting.  @HansDeBal are you also using a local / proxy repository?

It's possible that this is being caused by such proxies not including clojars in their default list of proxied remote repositories.

**Comment by HansDeBal** [comment] 2015-08-24 12:27
@pmonks Yep, that was the issue. We are ideed using a proxy. Added a proxy for the clojars-repo and it works now. Thanks!

**Comment by ohej** [comment] 2015-08-24 12:41
Closing as it was not an SDK issue

**Closed by ohej** 2015-08-24 12:41 UTC
Labels: bug
