### ISSUE TITLE
Add/Edit tags doesn't work with spring-loaded

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#207] opened 2014-08-14 15:18 UTC
Alfresco Tag/Tagging functionality gets broken when spring loaded is used.

The error can be traced to SerializationUtils.java: deserialize method.

The above method throws an exception indicating its unable to find the `org.alfresco.service.cmr.repository.NodeRef` class.

**Comment by skopf** [comment] 2015-03-03 12:18
I can also reproduce this problem. It is a general issue of spring-loaded in combination with Alfresco.

I get this Exception in a JUnit test with the following stacktrace:
```
Caused by: org.alfresco.error.AlfrescoRuntimeException: 02030394 Failed to deserialize
	at org.alfresco.util.SerializationUtils.deserialize(SerializationUtils.java:234)
	at org.alfresco.util.SerializationUtils.deserialize(SerializationUtils.java:273)
	at org.alfresco.util.ValueProtectingMap.protectValue(ValueProtectingMap.java:110)
	at org.alfresco.util.ValueProtectingMap.cloneMap(ValueProtectingMap.java:153)
	at org.alfresco.util.ValueProtectingMap.cloneMap(ValueProtectingMap.java:258)
	at org.alfresco.util.ValueProtectingMap.keySet(ValueProtectingMap.java:426)
	at org.alfresco.repo.rule.ruletrigger.OnPropertyUpdateRuleTrigger.havePropertiesBeenModified(OnPropertyUpdateRuleTrigger.java:126)
	at org.alfresco.repo.rule.ruletrigger.OnPropertyUpdateRuleTrigger.onUpdateProperties(OnPropertyUpdateRuleTrigger.java:261)
	at sun.reflect.GeneratedMethodAccessor737.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.alfresco.repo.policy.JavaBehaviour$JavaMethodInvocationHandler.invoke(JavaBehaviour.java:174)
	at com.sun.proxy.$Proxy86.onUpdateProperties(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor715.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.alfresco.repo.policy.PolicyFactory$MultiHandler.invoke(PolicyFactory.java:354)
	at org.alfresco.repo.policy.$Proxy234.onUpdateProperties(Unknown Source)
	at org.alfresco.repo.node.AbstractNodeServiceImpl.invokeOnUpdateProperties(AbstractNodeServiceImpl.java:465)
	at org.alfresco.repo.node.db.DbNodeServiceImpl.addAspectsAndProperties(DbNodeServiceImpl.java:548)
	at org.alfresco.repo.node.db.DbNodeServiceImpl.addAspectsAndProperties(DbNodeServiceImpl.java:445)
	at org.alfresco.repo.node.db.DbNodeServiceImpl.addAspect(DbNodeServiceImpl.java:783)
```

This problem is caused by this code line:
```java
    @SuppressWarnings("unchecked")
    public static <S extends Serializable> S protectValue(S value, Set<Class<?>> immutableClasses)
    {
        if (!mustProtectValue(value, immutableClasses))
        {
            return value;
        }
        // We have to clone it
        // No worries about the return type; it has to be the same as we put into the serializer
        return (S) SerializationUtils.deserialize(SerializationUtils.serialize(value));
    }
```

Even configuring spring-loaded to exclude the entire org.alfresco.service namespace does not help. I will debug spring-loaded and identify the root cause.....

**Comment by skopf** [comment] 2015-03-03 15:07
I finally figured out the root cause of this problem. It is a bug in spring-loaded.

When running without the spring-loaded java agent, a call within our webapp to
```java
sun.misc.VM.latestUserDefinedLoader()
```
during deserialization always returns
```
class org.apache.catalina.loader.WebappClassLoader
```

When running with the spring-loaded java agent, it returns
```
org.springsource.loaded.ChildClassLoader
```
for the object that has been serialized, but
```
sun.misc.Launcher$AppClassLoader@3432a325
```
for all objects that are contained in the serialized object.

Example:
When deserializing an ArrayList that contains QName (or NodeRef) objects, then the class java.util.ArrayList is resolved with the SpringLoaded classloader, but the class org.alfresco.service.namespace.QName is resolved with the root classloader.

The bug in spring-loaded:
The contract of the latestUserDefinedLoader() method is:
> Returns the first non-null class loader up the execution stack,
> or null if only code from the null class loader is on the stack.
When the spring-loaded java agent os loaded, it overwrites the classloader and intercepts specific method calls. The classes that intercept these methods belong to spring-loaded and are thus loaded by the root AppClassLoader that initially loaded the spring-loaded java agent during JVM startup.
So when latestUserDefinedLoader() walks up the call stack, the first non-null classloader it finds on a stack frame is this AppClassLoader from this woven-in spring-loaded interceptor.

**Comment by skopf** [comment] 2015-03-03 15:55
Raised this issue in spring-loaded with a detailed analysis:
https://github.com/spring-projects/spring-loaded/issues/107

**Comment by mindthegab** [comment] 2015-03-03 15:58
@skopf you rock! Thanks for troubleshooting this!

**Comment by binduwavell** [comment] 2015-05-07 20:30
@kopf ++ on you rocking! Thanks for finding and debugging this issue!

**Comment by nirajyadav** [comment] 2015-12-21 12:58
Hi Guys,
    is there any solution of this problem ? I am also facing same problem. Thanks for your help in advance. 

 org.springframework.extensions.webscripts.WebScriptException: 11210000 Wrapped Exception (with status template): 11210013 Failed to deserialize
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1127)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:489)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:551)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:619)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:399)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:280)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.alfresco.error.AlfrescoRuntimeException: 11210013 Failed to deserialize
	at org.alfresco.util.SerializationUtils.deserialize(SerializationUtils.java:234)
	at org.alfresco.util.SerializationUtils.deserialize(SerializationUtils.java:273)
	at org.alfresco.util.ValueProtectingMap.protectValue(ValueProtectingMap.java:110)
	at org.alfresco.util.ValueProtectingMap.cloneMap(ValueProtectingMap.java:153)
	at org.alfresco.util.ValueProtectingMap.cloneMap(ValueProtectingMap.java:258)
	at org.alfresco.util.ValueProtectingMap.keySet(ValueProtectingMap.java:426)
	at org.alfresco.repo.content.ContentServiceImpl.onUpdateProperties(ContentServiceImpl.java:253)
	at sun.reflect.GeneratedMethodAccessor388.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.alfresco.repo.policy.JavaBehaviour$JavaMethodInvocationHandler.invoke(JavaBehaviour.java:174)
	at com.sun.proxy.$Proxy69.onUpdateProperties(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor379.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.alfresco.repo.policy.PolicyFactory$MultiHandler.invoke(PolicyFactory.java:354)
	at org.alfresco.repo.policy.$Proxy204.onUpdateProperties(Unknown Source)
	at org.alfresco.repo.node.AbstractNodeServiceImpl.invokeOnUpdateProperties(AbstractNodeServiceImpl.java:465)
	at org.alfresco.repo.node.db.DbNodeServiceImpl.addAspectsAndProperties(DbNodeServiceImpl.java:548)
	at org.alfresco.repo.node.db.DbNodeServiceImpl.addAspectsAndProperties(DbNodeServiceImpl.java:445)
	at org.alfresco.repo.node.db.DbNodeServiceImpl.setProperty(DbNodeServiceImpl.java:1610)
	at sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.alfresco.repo.lock.mem.LockableAspectInterceptor.invoke(LockableAspectInterceptor.java:221)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy37.setProperty(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.alfresco.repo.tenant.MultiTNodeServiceInterceptor.invoke(MultiTNodeServiceInterceptor.java:104)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy37.setProperty(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.alfresco.repo.service.StoreRedirectorProxyFactory$RedirectorInvocationHandler.invoke(StoreRedirectorProxyFactory.java:224)
	at com.sun.proxy.$Proxy57.setProperty(Unknown Source)
	at org.alfresco.repo.node.MLPropertyInterceptor.invoke(MLPropertyInterceptor.java:251)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.node.NodeRefPropertyMethodInterceptor.invoke(NodeRefPropertyMethodInterceptor.java:260)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy37.setProperty(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at com.sun.proxy.$Proxy37.setProperty(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor655.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.alfresco.repo.audit.DisableAuditableBehaviourInterceptor.invoke(DisableAuditableBehaviourInterceptor.java:113)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at net.sf.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:46)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:159)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.transaction.RetryingTransactionInterceptor$1.execute(RetryingTransactionInterceptor.java:79)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
	at org.alfresco.repo.transaction.RetryingTransactionInterceptor.invoke(RetryingTransactionInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy37.setProperty(Unknown Source)
	at org.alfresco.repo.importer.ImporterComponent$NodeImporter.end(ImporterComponent.java:905)
	at org.alfresco.repo.importer.ImporterComponent.parserImport(ImporterComponent.java:424)
	at org.alfresco.repo.importer.ImporterComponent.importView(ImporterComponent.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.alfresco.repo.security.permissions.impl.AlwaysProceedMethodInterceptor.invoke(AlwaysProceedMethodInterceptor.java:34)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:46)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:159)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy107.importView(Unknown Source)
	at org.alfresco.module.org_alfresco_module_wcmquickstart.webscript.LoadWebSiteDataGet.executeImpl(LoadWebSiteDataGet.java:244)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
	... 32 more
Caused by: java.lang.ClassNotFoundException: org.alfresco.service.cmr.repository.NodeRef
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:626)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at java.util.ArrayList.readObject(ArrayList.java:791)
	at sun.reflect.GeneratedMethodAccessor323.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at java.io.ObjectStreamClass.__sljlrmi(ObjectStreamClass.java)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.alfresco.util.SerializationUtils.deserialize(SerializationUtils.java:230)
	... 141 more

**Comment by ohej** [comment] 2015-12-21 13:02
Unfortunately no, the issue lies within spring-loaded and it needs to be fixed there. We'll continue to monitor the issue, but it might look like we need to see if we can get resources to contribute a fix.

**Comment by nirajyadav** [comment] 2015-12-21 13:52
Thanks ohej !

   is there any workaround. I am using alfresco all in one archtype in eclipse and then added web quick start modules in my share and repo pom.xml. It failing with this error when i am trying to import web quick start sample data in my site. 

Appreciate your quick response.

**Comment by ohej** [comment] 2015-12-21 13:56
The only workaround right now is to disable spring-loaded, which means you won't get hot reloading for Java classes. 

If you want to disable spring-loaded, edit run.sh and remove `-javaagent:$springloadedfile -noverify` from the file. Run again, and the issue is gone - but at the cost of hot reloading of java classes.

**Comment by nirajyadav** [comment] 2015-12-21 14:24
Thank you Ohej. Appreciate your prompt response.

**Comment by chenzixia** [comment] 2016-11-01 02:21
the same exception ( Failed to deserialize ) is thrown also when implement custom category when i save the edit metadata form
<aspect name='fhcm:classification'>
         <title>xxxx data Classification</title>
         <parent>cm:classifiable</parent>
         <properties>
             <property name='fhcm:categories'>
               <title>Product Categories</title>
               <type>d:category</type>
               <mandatory>false</mandatory>
               <multiple>true</multiple>
               <index enabled='true'>
                  <atomic>true</atomic>
                  <stored>true</stored>
                  <tokenised>true</tokenised>
               </index>
            </property> 
         </properties>
       </aspect>

I'm usign SDK 2.2.0  and Alfresco Community 5.1.g jdk1.8 on Eclipse mars and springloaded-1.2.9.RELEASE.jar.

**Comment by jgoldhammer** [comment] 2016-11-26 22:03
This issue relates to spring-reloaded project. The referenced issue is not resolved here, so I will close the issue for now. Spring-reloaded is not supported in SDK 3 (instead use jrebel).

Thanks
Jens

**Closed by jgoldhammer** 2016-11-26 22:03 UTC
Labels: bug
