### ISSUE TITLE
Custom dependency overlays not available when running using run.sh

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#308] opened 2015-06-17 10:36 UTC
1. Add a custom share module dependency.
2. Run the project using run.sh (all-in-one archetype)
3. Observe if the module has loaded.

Step 3 results in nothing.

**Comment by bhagyas** [comment] 2015-06-17 11:04
Purged the entire project using `mvn clean -Ppurge` and now it seems to work.

Possibly related to #299

**Comment by mindthegab** [comment] 2015-07-30 18:20
This is a dupe of #299, closing.

**Closed by mindthegab** 2015-07-30 18:20 UTC
Labels: duplicate
