### ISSUE TITLE
Generating WAR files using mvn package results in WAR files with test resources.

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#321] opened 2015-06-26 13:39 UTC
Rename main folder in repo and share submodules to *test* from *main*.

**Comment by mindthegab** [comment] 2015-07-30 15:45
Hey @bhagyas,

thanks for the report but:

can you please focus on the problem rather than the solution?

There obviously is a rationale and a use case that we are supporting by allowing multi-environment properties to be neatly packaged at dev / staging / release time.

You seem to completely ignore this or (without bothering to write it) you are suggesting to drop this feature.

I will close this issue because, as is, this doesn't really mean much.

Please feel free to reopen if you get a chance to specify what the problem is more in detail and happy if you can propose a solution which doesn't entail braking existing functionalities.

**Comment by bhagyas** [comment] 2015-07-30 17:20
The rationale is that any server configuration should not be embedded in the deployment artefacts.

Default properties can be specified in the module.properties if required.

Certain properties, such as the database url and other properties introduce a large number of errors and makes it complicated for detecting issues with deployments.

**Comment by mindthegab** [comment] 2015-07-30 17:26
Default properties go in the alfresco-global.properties of the module, not in module.properties (that contains module metadata, not runtime properties).

I am oped to introduce a property that will allow you disabling embedding properties in the WAR, while still leaving the feature for people using it (and for backward compatibility)?

Makes sense?

**Comment by bhagyas** [comment] 2015-07-30 17:46
The properties that are in alfresco-global.properties primarily appear to be used for running integration tests. In our case, we were able to solve it by moving these to src/test from src/main.

For people who already use it as a way to deploy, I don't think there will be any impact from already disabling these, since this file would be already available in the classpath.

**Comment by mindthegab** [comment] 2015-07-30 17:52
I wonder if you are missing the point of the <env> variable.
Yes by default the env=local is selected, so yes the global properties included are the ones from the local integration test run.

But if you create another folder called src/main/properties/production/alfresco-global.properties and you run the build with -Penv=production the proper ones will be picked and packaged.

So again, to my question, say that we add a parameter called:

app.sdk.properties.include 

which by default is alfresco-global.properties but can be set to empty "" so that no property file is embedded in the final war, would this fit your requirement?

**Comment by bhagyas** [comment] 2015-07-30 17:53
Yeah, let's give it a try.

**Comment by mindthegab** [comment] 2015-08-06 18:04
Guess what @bhagyas , that feature is already in there, since 2.0.0 :+1: (I am starting not remembering all the features by heart, which is a *good* thing :)

The property is actually called:

app.properties.include 

and by default is **

Try to override it in your pom to set it as empty and it should work.

Let me know so I can close this issue.

**Comment by mindthegab** [comment] 2015-08-21 14:26
This is resolved.

**Closed by mindthegab** 2015-08-21 14:26 UTC
Labels: enhancement
