### ISSUE TITLE
Stopping a running maven instance needs 30 seconds...

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#406] opened 2016-09-14 12:04 UTC
When stopping a running Alfresco system inside the maven process, it needs 30 seconds to stop it.
This is very annoying when doing things which are not hot reloadable.

![image](https://cloud.githubusercontent.com/assets/3872101/18511258/084d5b82-7a83-11e6-8193-470df96d14ec.png)

Steps to repodruce:
1. Create a repository amp project with alfresco sdk 3 beta-3
2. Enable share deployment (`<enableShare>true</enableShare>`) in the pom.xml (I need this for testing purposes)
3. Execute run.sh
4. Try to stop it...

Environment:

![image](https://cloud.githubusercontent.com/assets/3872101/18511454/06785dba-7a84-11e6-88db-5d787b495292.png)

![image](https://cloud.githubusercontent.com/assets/3872101/18511339/738b57fa-7a83-11e6-83f3-2ffbee293033.png)

**Comment by gravitonian** [comment] 2016-09-15 10:37
I can see this on my Ubuntu box also, but it is not consistent. Sometimes it stops immediately, and sometimes it takes 15-30 seconds. Probably will not put this one as high priority, need to fix things like testing and code generation first...

**Comment by jgoldhammer** [comment] 2016-09-16 18:13
Ok, thanks. Only want to make sure that this is recognized...

**Comment by ohej** [comment] 2017-03-24 11:31
This seems to be an issue where Tomcat needs to close down resources properly. I have not been able to pinpoint a concrete way of reproducing the issue. I also see the same issue in a real deployment from time to time so I don't think this is something we can address in the scope of the SDK. Closing.

**Closed by ohej** 2017-03-24 11:31 UTC
