### ISSUE TITLE
Enable enterprise mode for repository amp project (Alfresco SDK 3 beta 1)

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#394] opened 2016-08-24 21:54 UTC
Following pom (modified with the help of your [guide](https://docs.google.com/document/d/1p5QR1Q8pVvMT9fh_aID5nraD5NP6ZrU1ztcgE_zHR-4/pub#h.g8ulc75vtjb7))

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>de.jgoldhammer</groupId>
    <artifactId>alfrescosdk3-repo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>alfrescosdk3-repo Platform Jar Module - SDK 3</name>
    <description>Platform JAR Module (to be included in the alfresco.war) - SDK 3</description>
    <packaging>jar</packaging>

    <properties>
        <alfresco.sdk.version>3.0.0-beta-1</alfresco.sdk.version>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Alfresco Data directory, which will contain:
                Content Store (i.e. the files we upload)
                Database (i.e. the metadata for the uploaded files)
                Search index (i.e. the indexed content and metadata)
             Configured in alfresco-global.properties with the 'dir.root' property.
                -->
        <alfresco.data.location>${session.executionRootDirectory}/alf_data_dev</alfresco.data.location>

        <!-- Duplicated with alfresco.solrHome in the plugin, we need them out here to do filtering -->
        <solr.home>${alfresco.data.location}/solr</solr.home>
        <solr.model.dir>${solr.home}/alfrescoModels</solr.model.dir>
        <solr.content.dir>${solr.home}/index</solr.content.dir>

        <!-- Properties used in dependency declarations, you don't need to change these -->
        <alfresco.groupId>org.alfresco</alfresco.groupId>

        <!-- Alfresco Platform webapp version, this is the original Alfresco webapp that will be
            customized and then deployed and run by the tomcat maven plugin when
            executing for example $ mvn clean install alfresco:run -->
        <alfresco.platform.version>5.1.1</alfresco.platform.version>
        <!-- Alfresco Share version, so we can bring in correct alfresco-share-services artifact -->
        <alfresco.share.version>5.1.1</alfresco.share.version>
    <alfresco.surf.version>6.3</alfresco.surf.version>
    <alfresco.platform.war.artifactId>alfresco-enterprise</alfresco.platform.war.artifactId>

        <!-- Alfresco Repo Database configuration.
           By default it uses a flat file H2 database to be able to run embedded.
           The H2 database implementation is brought in via the tomcat7-maven-plugin as a dependency.
           The data files for the H2 database will be created in a relative path, such as alf_data_dev/h2_data/alf_dev,
           see alfresco.db.url below.
           For more information about the db parameters see:http://www.h2database.com/html/features.html
        -->
        <alfresco.db.name>alf_dev</alfresco.db.name>
        <alfresco.db.username>alfresco</alfresco.db.username>
        <alfresco.db.password>alfresco</alfresco.db.password>
        <alfresco.db.params>AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;MVCC=FALSE;LOCK_MODE=0
        </alfresco.db.params>
        <alfresco.db.url>jdbc:h2:${alfresco.data.location}/h2_data/${alfresco.db.name};${alfresco.db.params}
        </alfresco.db.url>
        <alfresco.db.datasource.class>org.h2.jdbcx.JdbcDataSource</alfresco.db.datasource.class>

        <!-- JRebel Hot reloading of classpath stuff and web resource stuff -->
        <jrebel.version>1.1.6</jrebel.version>

        <!-- Environment to use, Alfresco Maven Plugin will copy alfresco-global.properties from this directory -->
        <env>local</env>
    </properties>

    <!-- This will import the dependencyManagement for all artifacts in the selected Alfresco platform.
            NOTE: You still need to define dependencies in your POM,
            but you can omit version as it's enforced by this dependencyManagement.
            NOTE: It defaults to the latest version this SDK pom has been tested with,
            but alfresco version can/should be overridden in your project's pom
    -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${alfresco.groupId}</groupId>
                <artifactId>alfresco-platform-distribution</artifactId>
                <version>${alfresco.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- The main Alfresco Repo dependency for compiling Java code in src/main/java -->
        <dependency>
            <groupId>${alfresco.groupId}</groupId>
            <artifactId>alfresco-repository</artifactId>
        </dependency>
    <dependency>
        <groupId>com.softwareloop</groupId>
        <artifactId>uploader-plus-repo</artifactId>
        <version>1.2</version>
        <type>amp</type>
    </dependency>
    </dependencies>

    <build>
        <plugins>
            <!--
                The Alfresco Maven Plugin contains all the logic to run the extension
                in an embedded Tomcat with the H2 database.
                -->
            <plugin>
                <groupId>org.alfresco.maven.plugin</groupId>
                <artifactId>alfresco-maven-plugin</artifactId>
                <version>${alfresco.sdk.version}</version>
                <configuration>
                    <!-- Default is to run with a Community edition, change to 'enterprise' if using Enterprise edition -->
                    <alfrescoEdition>enterprise</alfrescoEdition>

                    <!-- We need the flat file H2 database to run the Repo -->
                    <enableH2>true</enableH2>
                    <!-- This is a platform extension JAR, so we need the platform webapp (alfresco.war) -->
                    <enablePlatform>true</enablePlatform>
                    <!-- Enable Solr so we can use search, our Repo extension probably need search -->
                    <enableSolr>true</enableSolr>
                    <!-- We don't need the share.war if we don't have any UI extensions -->
                    <enableShare>false</enableShare>

                    <!--
                       JARs and AMPs that should be overlayed/applied to the Platform/Repository WAR
                       (i.e. alfresco.war)
                       No need to include our self...
                       -->
                    <platformModules>
                        <!-- This AMP is needed if we are going to access the platform webapp from a Share webapp -->
                        <moduleDependency>
                            <groupId>${alfresco.groupId}</groupId>
                            <artifactId>alfresco-share-services</artifactId>
                            <version>${alfresco.share.version}</version>
                            <type>amp</type>
                        </moduleDependency>

            <moduleDependency>
                    <groupId>de.fmaul</groupId>
                    <artifactId>javascript-console-repo</artifactId>
                    <version>0.6</version>
                    <type>amp</type>
            </moduleDependency>

            <moduleDependency>
                <groupId>com.softwareloop</groupId>
                <artifactId>uploader-plus-repo</artifactId>
                <version>1.2</version>
                <type>amp</type>
            </moduleDependency>
                    </platformModules>
                </configuration>
            </plugin>

            <!-- Build an AMP if 3rd party libs are needed by the extension -->
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.6</version>
                <executions>
                    <execution>
                        <id>build-amp-file</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <appendAssemblyId>false</appendAssemblyId>
                            <descriptor>src/main/assembly/amp.xml</descriptor>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.alfresco.maven.plugin</groupId>
                        <artifactId>alfresco-maven-plugin</artifactId>
                        <version>${alfresco.sdk.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

            <!-- Hot reloading with JRebel -->
            <plugin>
                <groupId>org.zeroturnaround</groupId>
                <artifactId>jrebel-maven-plugin</artifactId>
                <version>${jrebel.version}</version>
                <executions>
                    <execution>
                        <id>generate-rebel-xml</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!--
                      addResourcesDirToRebelXml - default is false
                      Required if the resource directories are to be added to rebel.xml
                    -->
                    <addResourcesDirToRebelXml>true</addResourcesDirToRebelXml>

                    <!-- Always generate the rebel.xml file no matter what timestamps -->
                    <alwaysGenerate>true</alwaysGenerate>
                </configuration>
            </plugin>
        </plugins>

        <resources>
            <!-- Filter the resource files in this project and do property substitutions -->
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <testResources>
            <!-- Filter the test resource files in this project and do property substitutions -->
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>
    </build>

    <!--
        Alfresco Maven Repositories
        -->
    <repositories>
        <repository>
            <id>alfresco-public</id>
            <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
        </repository>
        <repository>
            <id>alfresco-public-snapshots</id>
            <url>https://artifacts.alfresco.com/nexus/content/groups/public-snapshots</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>alfresco-plugin-public</id>
            <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
        </pluginRepository>
        <pluginRepository>
            <id>alfresco-plugin-public-snapshots</id>
            <url>https://artifacts.alfresco.com/nexus/content/groups/public-snapshots</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

</project>

```

brings up following error:

```
/run.sh
[INFO] Scanning for projects...
Downloading: https://oss.sonatype.org/content/repositories/orgalfresco-1037/org/alfresco/alfresco-platform-distribution/5.1.1/alfresco-platform-distribution-5.1.1.pom
Downloading: https://repo1.maven.org/maven2/org/alfresco/alfresco-platform-distribution/5.1.1/alfresco-platform-distribution-5.1.1.pom
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/alfresco-platform-distribution/5.1.1/alfresco-platform-distribution-5.1.1.pom
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/org/alfresco/alfresco-platform-distribution/5.1.1/alfresco-platform-distribution-5.1.1.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.alfresco:alfresco-platform-distribution:pom:5.1.1 in alfresco-sdk-staging (https://oss.sonatype.org/content/repositories/orgalfresco-1037/) @ line 73, column 25
[ERROR] 'dependencies.dependency.version' for org.alfresco:alfresco-repository:jar is missing. @ line 85, column 21
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project de.jgoldhammer:alfrescosdk3-repo:1.0-SNAPSHOT (/Users/jgoldhammer/development/sources/alfrescosdk3-repo/pom.xml) has 2 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.alfresco:alfresco-platform-distribution:pom:5.1.1 in alfresco-sdk-staging (https://oss.sonatype.org/content/repositories/orgalfresco-1037/) @ line 73, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.alfresco:alfresco-repository:jar is missing. @ line 85, column 21
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

What I am doing wrong here?

**Comment by jgoldhammer** [comment] 2016-08-24 22:05
Workaround:
- Add version element to the repository dependency...

```
<dependency>
            <groupId>${alfresco.groupId}</groupId>
            <artifactId>alfresco-repository</artifactId>
            <version>${alfresco.platform.version}</version>
</dependency>
```

Can you add this in your pom template which is used to generate the repo pom?

**Comment by gravitonian** [comment] 2016-09-05 14:50
Cannot reproduce, make sure to run now with latest beta-3, update repo path also in settings.xml

**Comment by jgoldhammer** [comment] 2016-09-06 09:05
I will try soon. Please wait for feedback a little bit before closing an issue. Thanks...

**Comment by sujaypillai** [comment] 2016-09-07 16:42
Getting the same error as @jgoldhammer and on adding the suggestion from him get the below error using 3.0.0-beta-3
`
$  mvn clean install -DskipTests=true alfresco:run -U
[INFO] Scanning for projects...
Downloading: https://oss.sonatype.org/content/repositories/orgalfresco-1039/org/alfresco/alfresco-platform-distribution/5.1.1/alfresco-platform-distribution-5.1.1.pom
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/alfresco-platform-distribution/5.1.1/alfresco-platform-distribution-5.1.1.pom
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/org/alfresco/alfresco-platform-distribution/5.1.1/alfresco-platform-distribution-5.1.1.pom
Downloading: https://repo.maven.apache.org/maven2/org/alfresco/alfresco-platform-distribution/5.1.1/alfresco-platform-distribution-5.1.1.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.alfresco:alfresco-platform-distribution:pom:5.1.1 in alfresco-sdk-staging (https://oss.sonatype.org/content/repositories/orgalfresco-1039/) @ line 73, column 25
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.jabil:jabil-repo:1.0-SNAPSHOT (C:\jabilmaven\Alfresco\code\jabil-repo\pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Could not find artifact org.alfresco:alfresco-platform-distribution:pom:5.1.1 in alfresco-sdk-staging (https://oss.sonatype.org/content/repositories/orgalfresco-1039/) @ line 73, column 25 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

`

**Comment by gravitonian** [comment] 2016-09-08 13:26
Hi,

Tried again with Beta-3 and removed all my alfresco-platform-distribution artifacts from local repo.

You should see something like:

```
Downloading: https://artifacts.alfresco.com/nexus/content/groups/private/org/alfresco/alfresco-platform-distribution/5.1.1/alfresco-platform-distribution-5.1.1.pom
Downloaded: https://artifacts.alfresco.com/nexus/content/groups/private/org/alfresco/alfresco-platform-distribution/5.1.1/alfresco-platform-distribution-5.1.1.pom (8 KB at 1.7 K
```

Can you access this file from the browser and verify that you have access to the enterprise artifacts?

**Comment by ohej** [comment] 2016-09-08 14:10
Do you have the enterprise repositories in your pom.xml? 
@gravitonian, I suspect you have them in settings.xml? 
@jgoldhammer can you try and add:
```
            <repositories>
                <repository>
                    <id>alfresco-private-repository</id>
                    <url>https://artifacts.alfresco.com/nexus/content/groups/private</url>
                </repository>
            </repositories>
```

To your pom? (and make sure you have a `<server>` in settings.xml matching the ID with valid credentials

**Comment by ohej** [comment] 2016-09-08 14:11
.... that "comment and close" button is dangerously close to "Comment" :P reopening, sorry!

**Comment by gravitonian** [comment] 2016-09-08 15:22
Yes,

I have this in my settings.xml:

```
 <!-- Alfresco Enterprise artifacts -->
	<repository>
                <id>alfresco-private-repository</id>
                <url>https://artifacts.alfresco.com/nexus/content/groups/private</url>
        </repository>
```
And associated username/password config.

**Comment by sujaypillai** [comment] 2016-09-09 05:14
I got this working by adding the enterprise repositories in pom.xml. It also works for me if i have the same entry in settings.xml.
Can you please suggest which would be the best place to have this value (pom.xml/settings.xml)?

**Comment by ohej** [comment] 2016-09-09 10:04
For the sake of reproducibility and stable builds I would recommend you add them to your pom. This way you only have to provide credentials in your `settings.xml`.

Previously the `enterprise` profile would add in the repository, but since we don't have the parent pom the profile doesn't exist. 

We will investigate if this can be added by the Alfresco Maven Plugin, but as I mentioned above, it might be possible.

**Comment by jgoldhammer** [comment] 2016-09-09 12:33
Ok, adding repository in pom works for me without adding the version to the dependency.
Thanks for this.

Maybe another idea to solve this issue would be to enable an option in the archetype generator. Often users know the alfresco edition before generating the project. So what about adding an configuration option for enterprise/community and alfresco version? The archetype generator than could add the alfresco-private-repository in the pom.xml...

What do you think?

**Comment by ohej** [comment] 2016-09-09 12:57
@jgoldhammer it's a good idea, however Maven archetypes does not offer us that much flexibility. We can only do basic substitution in files and directories, no conditional things.

This is why we want to embrace the Yeoman generator that Bindu has been working on - it will allow us to do stuff like this and much more (add new modules, dependencies, scaffolding etc). 

I'm hopeful that we can have the plugin add the repository but in case we can't this will either have to be done manually or via Yeoman (which will not be required but optional).

**Comment by jgoldhammer** [comment] 2016-09-09 19:40
I forgot- Maven is not JHipster :-) 

IMHO, Yeoman would be cool, but it should be than officially supported and maintained by Alfresco people additionally to Bindu...

**Comment by gravitonian** [comment] 2016-09-12 10:32
Enterprise repo now part of the POMs:

```
  <!-- Alfresco Enterprise Edition Artifacts, put username/pwd for server in settings.xml -->
        <repository>
            <id>alfresco-private-repository</id>
            <url>https://artifacts.alfresco.com/nexus/content/groups/private</url>
        </repository>
```

**Comment by jgoldhammer** [comment] 2016-09-13 13:28
Thanks for adding this. Will help in the future...

**Comment by ohej** [comment] 2016-09-13 13:30
Reopening again. Adding them permanently to the pom will result in authentication errors in the logs if you don't have credentials in `settings.xml`. 

This means everyone developing on community edition will see errors all over. 

We should investigate if the plugin can add them

**Comment by gravitonian** [comment] 2016-09-13 13:40
I thought about that, and tested without auth info in settings.xml, no errors in the logs as the artifacts were found before the private repo were needed. 
Should I get errors by just commenting out the server user/pwd in settings.xml ???

**Comment by ohej** [comment] 2016-09-13 13:43
That would probably be because you already have the artifacts. When Maven is resolving dependencies and it will check on all of the repositories that are available directly or indirectly in the pom which will trigger authentication issues. I'm happy if I'm proven wrong, I've just seen this too many times in the past. Let me do some tests

**Comment by ohej** [comment] 2017-03-23 15:50
We include the enterprise repositories by default. As for SDK testing we are separating out the archetype tests (when building the SDK itself) so a profile has to be activated to execute the tests against enterprise artifacts

**Closed by ohej** 2017-03-23 15:50 UTC
