### ISSUE TITLE
All-in-one archetype generates invalid pom.xml files for submodules

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#293] opened 2015-05-26 14:20 UTC
```   
     <dependency>
            <groupId>${alfresco.groupId}</groupId>
            <artifactId>${alfresco.se.loftux.extensions.kanban.repo.artifactId}</artifactId>
            <version>${alfresco.version}</version>
            <type>war</type>
        </dependency>
        <!-- Demonstrating the dependency / installation of the se.loftux.extensions.kanban.repo AMP developed in the 'se.loftux.extensions.kanban.repo-amp' module -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>se.loftux.extensions.kanban.repo-amp</artifactId>
            <version>${project.version}</version>
            <type>amp</type>
        </dependency>
```

Related to the issue #292

**Comment by ohej** [comment] 2015-06-08 07:13
As said on #292 I can't reproduce this issue, need more info

**Comment by ohej** [comment] 2015-06-08 08:13
Assuming this was the same issue as #292 and can't be reproduced. Closing

**Closed by ohej** 2015-06-08 08:13 UTC
