### ISSUE TITLE
Modifications of original client-side files are not picked up

### ISSUE THREAD

**Issue by Sheldor5** [Alfresco/alfresco-sdk#327] opened 2015-08-06 13:07 UTC
It seems that all changes of original client-side files are not picked up by running the project with integration-test profile.

Example:
If the file {share-war}/js/alfresco.js is modified in the AMP module (so it should overwrite the original one) the file is not being overwritten by the modified one from {maven-project}/src/main/amp/web/js/alfresco.js.

Am I missing something?

**Comment by mindthegab** [comment] 2015-08-06 17:07
This is probably a dupe of issue#255 and specifically because of https://github.com/Alfresco/alfresco-sdk/issues/255#issuecomment-73956728.

Workaround is simply putting your stuff in 

src/main/resources/META-INF/resources/

and then it will be picked up from the classpath (as per Servlet3 spec).

More in general: we are trying to work the platform in a way that you *don't need* to override core files. Can I understand a bit more of what you are trying to do?

**Closed by mindthegab** 2015-08-06 17:07 UTC
Labels: bug

**Comment by Sheldor5** [comment] 2015-08-07 10:16
Oh sorry I haven't seen the dup.

I extended the actions generation inside the actions.js file to handle a custom type of action which I am currently developing (https://github.com/Sheldor5/alfresco-share-clipboard) and I haven't found another way than overwriting the OOTB client-side javascript file.

**Comment by Sheldor5** [comment] 2015-08-07 10:48
I have moved everything from:
src\main\amp\web\components\documentlibrary
to:
src\main\resources\META-INF\resources\components\documentlibrary
but the changes are still not visible nor picked up (clean, restart, tried everything) so your suggested workaround is not working.
Could you give me more detailed instructions on how for example overwriting the OOTB actions.js file?

**Comment by fmaul** [comment] 2015-09-11 08:58
If you use `src\main\resources\META-INF\resources` it puts a `resources` folder in your AMP. Then you can add a mapping `/resources=/` in your `filemapping.properties` to have it installed to the correct path. 

The only issue is that the build process only copies the minimized javascript files to the AMP and that is not really helping for development.
