### ISSUE TITLE
Alfresco is running without Share Services. See your System Administrator for more details.

### ISSUE THREAD

**Issue by kodermax** [Alfresco/alfresco-sdk#445] opened 2017-03-29 07:28 UTC
When I have alfresco sdk 3.0, i have this error.
![image](https://cloud.githubusercontent.com/assets/590985/24446972/17cb836a-1478-11e7-8f4b-349f5e109097.png)

**Comment by ohej** [comment] 2017-03-29 15:12
Did you build SDK 3 from source or did you use the beta? Which version of platform and share are you running?

**Comment by kodermax** [comment] 2017-03-31 05:21
I did build SDK 3 from source. I have 5.2.e platfom and share version.

**Comment by sujaypillai** [comment] 2017-04-02 22:14
I created the AIO project using the below command --
`
mvn archetype:generate -DarchetypeGroupId=org.alfresco.maven.archetype -DarchetypeArtifactId=alfresco-allinone-archetype -DarchetypeVersion=3.0.0 -DinteractiveMode=false -DgroupId=com.demo -DartifactId=demoapp
`
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=300m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:2.2:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:2.2:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] --- maven-archetype-plugin:2.2:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype repository missing. Using the one from [org.alfresco.maven.archetype:alfresco-allinone-archetype:2.2.0] found in catalog remote
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: alfresco-allinone-archetype:3.0.0
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.demo
[INFO] Parameter: artifactId, Value: demoapp
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: package, Value: com.demo
[INFO] Parameter: packageInPathFormat, Value: com/demo
[INFO] Parameter: package, Value: com.demo
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: groupId, Value: com.demo
[INFO] Parameter: artifactId, Value: demoapp
[INFO] Parent element not overwritten in /Users/sujay/Dev/demoapp/demoapp-platform-jar/pom.xml
[INFO] Parent element not overwritten in /Users/sujay/Dev/demoapp/demoapp-share-jar/pom.xml
[INFO] Parent element not overwritten in /Users/sujay/Dev/demoapp/integration-tests/pom.xml
[INFO] project created from Archetype in dir: /Users/sujay/Dev/demoapp
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.978 s
[INFO] Finished at: 2017-04-03T05:53:12+08:00
[INFO] Final Memory: 12M/245M
[INFO] ------------------------------------------------------------------------

<img width="1155" alt="screenshot 2017-04-03 06 05 00" src="https://cloud.githubusercontent.com/assets/3936714/24591456/1c6c58c6-1834-11e7-96f7-da825d9205c6.png">

Calling the following URL - `http://localhost:8080/alfresco/api/-default-/private/alfresco/versions/1/modulepackages/` shows share-services installed as a module
<img width="935" alt="screenshot 2017-04-03 06 11 49" src="https://cloud.githubusercontent.com/assets/3936714/24591477/9ca700cc-1834-11e7-8de1-13a9ea6e9be5.png">

**Comment by ladenberger** [comment] 2017-04-03 11:03
Same problem here using:
Alfresco SDK 3 Release
Alfresco + Share Enterprise 5.2

Any new information regarding this issue?

**Comment by ohej** [comment] 2017-04-05 13:46
As far as I can tell, this is an issue with the way Share checks the module and then proceeds to cache the results. I cannot seem to figure out what is going on, because as @sujaypillai points out, the module is installed, and calling APIs directly gives the correct results. 

It's currently not clear if this is something the SDK causes or if it's a bug in Share. Needs more investigation.

**Comment by ohej** [comment] 2017-04-05 13:46
I should add that, for now, all though the message is annoying it can be ignored. All functionality seem to work even though the notification appears.

**Comment by ohej** [comment] 2017-04-05 14:06
Some quick testing shows that there may be a misconfiguration in the share-config-custom.xml that is bundled with the SDK. 

Can you try changing the file `src/test/resources/share/share-config-custom.xml`. Look for the last `<endpoint>` section and change the `<endpoint-url>` to be `<endpoint-url>${alfresco.repo.url}/api</endpoint-url>`

So in total it looks like this:
```
            <endpoint>
                <id>alfresco-api</id>
                <parent-id>alfresco</parent-id>
                <name>Alfresco Public API - user access</name>
                <description>Access to Alfresco Repository Public API that require user authentication.
                    This makes use of the authentication that is provided by parent 'alfresco' endpoint.</description>
                <connector-id>alfresco</connector-id>
                <endpoint-url>${alfresco.repo.url}/api</endpoint-url>
                <identity>user</identity>
            </endpoint>
```

and report back if this solved both the "Share is running with out share services" and the CMM issue?

**Comment by ohej** [comment] 2017-04-05 14:28
The fix I suggested above seems to fix both issues (missing Share services) and the CMM error. I've confirmed on multiple machines/environments and the fix seems solid. Can you guys confirm?

**Comment by ladenberger** [comment] 2017-04-05 17:02
Hi Ole. Thanks for the fast response and the fix. I will try it tomorrow morning and give you feedback asap.

**Comment by ladenberger** [comment] 2017-04-06 07:25
Good morning Ole, I can config that this fixed the problem. Thanks!

**Comment by ohej** [comment] 2017-04-06 08:34
Excellent, thanks @ladenberger. 
I committed a fix in 68dda3b211796556c834de7bae76dcc5317c79b9 which will be included in the next release.

**Closed by ohej** 2017-04-06 08:34 UTC
Labels: bug

**Comment by kranthi23** [comment] 2018-01-05 11:29
Hi @ohej ,

I did build using alfresco **sdk 3.0.1** for both platform and share side with jar type.After doing build and deployed in another server for testing I am getting error.
[alfrescotomcat-2-stdout.2018-01-05.log](https://github.com/Alfresco/alfresco-sdk/files/1606420/alfrescotomcat-2-stdout.2018-01-05.log)

I am pointing to **8090** installed with **AC-5.2 version**.And also I checked in my code **share-config-custom.xml** whether it contains **8080** port anywhere but it's not having that.Please find the log files.

 
 2018-01-05 15:41:59,530  INFO  [webscripts.connector.RemoteClient] [http-apr-8090-exec-3] Exception calling (GET) http://localhost:8080/alfresco/s/api/admin/restrictions?guest=true
 2018-01-05 15:41:59,534  INFO  [webscripts.connector.RemoteClient] [http-apr-8090-exec-3] Error status 503 Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
 org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
![login](https://user-images.githubusercontent.com/20297825/34607449-b26ff3ca-f239-11e7-8a2c-3550022c881b.PNG)

**Comment by OMIMV** [comment] 2019-01-13 10:20
Hi All,
I;m madhu here
I have add above in xml, still i'm getting same issue,can some help me please
